Terminal = "kitty"
FileManager = "dolphin"
Browser = "zen-browser"
Menu = "walker"
Discord = "discord --enable-features=UseOzonePlatform --ozone-platofm=wayland --start-minimized"
WhatsApp = "flatpak run com.rtosta.zapzap"
